Drewol/unnamed-sdvx-clone

- Main/Camera.cpp
- Main/Input.cpp
- Main/Scoring.cpp
This mostly fixes #26 in the original repo: lasers on linux now work properly instead of always having a leniency of 1.
> use fabs where needed

- Main/GUI/SongSelectItem.cpp
Now displays full string instead of first char. Should also still work on Windows.
> Fix grade string display on linux

- Graphics/include/Graphics/Image.hpp
- Graphics/src/Image.cpp
- Main/GUI/SongSelectStyle.cpp
With  a sample database of several hundred songs, this drops memory usage from 3gb  down to below 1gb.
Also added a commented out section for evicting artwork from the cache based on last use time.
> Resize all cover art > 150x150 to 150x150

- Main/Scoring.cpp
Allows movement when on the wrong side of the laser, even through the laser if going the opposite direction. This matches arcade behavior.
> laser fixes

- Main/Input.cpp
I was getting an assertion failure when leaving the settings menu saying a duplicate delegate handler was being added, this looks to be the case (and I think the only one, at that).
> Properly remove the mouse motion handler in Input

- Main/Application.cpp
- Shared/src/Path.cpp
Removed an unused extension related function while I was at it, didn't want to update it for no reason.
> Fix issue with skins having `.` in their file path

- Beatmap/src/BeatmapFromKSH.cpp
Also split the effect param at the '>' character.
Fix some maps with custom effects that are using percentage sign like this:
`#define_filter ft10 type=Retrigger;waveLength=0.250000;rate=100%;mix=0%>95%;updatePeriod=1.000000`
> Parse percentage value in custom fxs and filters.

- Beatmap/include/Beatmap/AudioEffects.hpp
- Beatmap/include/Beatmap/Beatmap.hpp
- Beatmap/src/AudioEffects.cpp
- Beatmap/src/Beatmap.cpp
- Beatmap/src/BeatmapFromKSH.cpp
- Main/Audio/AudioPlayback.cpp
- Main/Audio/AudioPlayback.hpp
Since there's already a fxtrack, the audio tracks for SwitchAudio effect are referred as switchables in code.
Notes:
- Beatmap is changed.
- SwitchAudio is treated as a AudioEffect, yet it is being handle by special cases to avoid using DSP.
- Added a m_musicVolume member to ensure the volume stay consistent when switching between tracks (including fxtrack)
- Switchable tracks does not load if fxtrack exists. Just like other effects.
- [Here](https://1drv.ms/u/s!AhmEP92g-Ak5gqEqumZH62lnYttbzg) is a example ksh map.
Other:
- Stop Gate effect from updating its gate in every frame, when the effect is activated by laser. (Updating gate reset the timer so the effect can not be heard).
> Add support for SwitchAudio effect

- Beatmap/src/BeatmapFromKSH.cpp
MapTime is integer. If there are a lot of BPM and beat changes, the `time` in each TimingPoint is shifting 
a little bit due to lack of precision. (And the `time` in these TimingPoints are being passed to DSP's lastTimingPoint, which is used to determine the repeating pattern of the Retrigger effect.)
timingPoints in USC:
the counterparts in KSM editor:
At the end of the map they are already 4ms apart, I'd imagine it'll only get worse if more timingPoints is created.
This PR fixed this issue by temporary storing a double precision time and using it instead of MapTime.
> Fix a precision error when calculating TimingPoints

- Beatmap/include/Beatmap/Beatmap.hpp
- Beatmap/src/Beatmap.cpp
- Beatmap/src/BeatmapFromKSH.cpp
- Main/SongSelect.cpp
There were a few issues with the preview system. I got rid of the delay hack and replaced it with a nicer implementation handled by the `PreviewPlayer` struct. 
In cases where different difficulties of a song have differing previews, the correct one will now be played when its difficulty is selected.
The final commit adds support for a new KSH metadata field, `previewfile`. This allows charts to define a specific file in the song directory to be played as a preview in lieu of setting an offset and duration. If a `previewfile` is present, the preview offset and duration fields are ignored; if there is no `previewfile` then they retain their previous behavior.
> Fixes and improvements to preview handling

- Main/Camera.cpp
m_spinType was not initialized, so there was a chance that it would be set to one of the spin enum values. When this happened it would cause a roll as soon as the first tick is calculated. This results in m_spinRoll being miscalculated and set to NaN. This will prevent the track from rendering at the start of a song.
The fix simply sets m_spinType  to None in the constructor.
> Fix uninitialized spin type in camera

- Audio/src/AudioStreamBase.cpp
When `m_samplePos` is negative, `m_samplePos >= m_samplesTotal` returns true since `m_samplePos` is converted to unsigned integer.
Some of charts on Nautica had this problem. Example: https://ksm.dev/songs/bca80f60-d3e2-11e9-98db-77b73288e072
> Fixed: charts with high offset value ends as soon as the play starts

- Shared/src/Unix/Path.cpp
Was causing Conditional jump or move depends on uninitialised value(s) under valgrind
> Stop at the end of String Path::Normalize

- Main/LaserTrackBuilder.cpp
It's currently getting the size for the second entry texture instead of an exit texture.
> Fix getting size of wrong texture

- Main/Game.cpp
Able to reproduce consistently by holding down the BT buttons and spamming Start during the transition screen from song select to chart. 
What happens is at some point at the end of the transition screen from song select to play `Game.cpp` will accept input and when pressing the manual exit keys it will change screens before `TransitionScreen.cpp` finishes and cleans up causing an Access Violation at `m_tickableToLoad->Tick(deltaTime);` in `TransitionScreen.cpp`
> Fix crash by exiting before transition end

- Graphics/src/ImageLoader.cpp
Non ascii characters can be badly encoded if file is open thinking that it is encoded in UTF8
> Remove non-ascii characters

- Main/Game.cpp
- Main/Scoring.cpp
Some people noticed that they stopped getting earlys and lates when having large magnitude input offsets. I looked at where the input offset was applied and found it was correctly applied when a tick has  been consumed by a button press:
https://github.com/Drewol/unnamed-sdvx-clone/blob/41d9c670e95c9033b80010ce2dbfa67d6cdf7874/Main/Scoring.cpp#L776
However when the game judges if a tick has been missed without a button hit, there is no input offset applied:
https://github.com/Drewol/unnamed-sdvx-clone/blob/41d9c670e95c9033b80010ce2dbfa67d6cdf7874/Main/Scoring.cpp#L653
This seems incorrect, since it would mean that the tick could be removed before the actual good or crit window starts (with the input offset applied)
As a potential fix I added the input offset second delta calculation. …
> Possibly improve input offset when grading if a note was missed

- Main/include/Application.hpp
- Main/include/ShadedMesh.hpp
- Main/src/Application.cpp
- Main/src/ShadedMesh.cpp
- docs/source/shadedmesh.rst
When using shaded mesh with chart provided backgrounds, materials can only be loaded from the skin directory. This patch adds an option to specify the path that the materials should be loaded from.
> Add option to specify path for shaded mesh

- Audio/src/Windows/AudioOutput_WASAPI.cpp
Ensure detected MixFormat is supported, and use the returned closestFormat if not
> Ensure detected MixFormat is supported, and use the returned closestFormat if not

- Main/src/DownloadScreen.cpp
The download screen for Nautica, in specific `DownloadScreen::m_ProcessArchiveResponses`, had two problems.
1. After extracting a chart archive, it didn't free the archive handle properly.
2. For certain chart archives with non-ASCII pathnames, the program could crash.
A bug still exists where certain archives with non-ASCII pathnames are not extracted properly.
> Fixed a crash and a resource leak in DownloadScreen.

- Main/include/DownloadScreen.hpp
- Main/include/MultiplayerScreen.hpp
- Main/src/DownloadScreen.cpp
- bin/skins/Default/scripts/downloadscreen.lua
This changeset adds a lua function to DownloadScreen which takes a url to a preview audio file, downloads it to the `preview` directory and then plays it.
I've also updated the default skin to have support for nautica's previews.
> Add preview support for nautica

- Main/include/Application.hpp
- Main/include/Scoring.hpp
- Main/src/Application.cpp
- Main/src/Game.cpp
- Main/src/Scoring.cpp
Changed the logic based on the following hypothesis:
1. When each tick is being passed, the button must be held for the moment. (#355)
2. However, the last tick will be counted as long as...
a. the previous hold tick was hit, and
b. the last button released happened inside the "near window" of the end of the hold note.
Needs some playtesting though.
> Reworked how hold notes work.

- Main/src/Scoring.cpp
This simple change has two purposes.
1. To respect changes done in 13090a7f
2. To enable controlling hold note judgements separately
> Made long note judgements use hold window instead of near window

- Beatmap/src/BeatmapFromKSH.cpp
- Main/include/Camera.hpp
Conversion of manual tilt values was changed in KSM so that it is scaled based off of 10 degrees. This probably happened in update 1.70a, where roll angles were changed to be inline with SDVX and USC. This PR updates USC's manual tilt value conversion to reflect these changes.
Since there's no mention of this change in the [KSH format doc](https://github.com/m4saka/ksh/blob/master/ksh_format.md), backwards compatibility shouldn't be an issue.
> Update manual tilt conversion to be KSM correct

- Main/src/Application.cpp
- Main/src/DownloadScreen.cpp
> Set the locale to `.UTF-8` to force C lib functions such as fopen use UTF-8

- Beatmap/include/Beatmap/MapDatabase.hpp
- Beatmap/src/MapDatabase.cpp
- Main/include/ChatOverlay.hpp
- Main/include/DownloadScreen.hpp
- Main/include/Game.hpp
- Main/include/GameConfig.hpp
- Main/include/GameplaySettingsDialog.hpp
- Main/include/HitStat.hpp
- Main/include/MultiplayerScreen.hpp
- Main/include/Scoring.hpp
- Main/include/SkinHttp.hpp
- Main/include/SongSelect.hpp
- Main/include/TCPSocket.hpp
- Main/src/CalibrationScreen.cpp
- Main/src/Game.cpp
- Main/src/GameConfig.cpp
- Main/src/GameplaySettingsDialog.cpp
- Main/src/HitStat.cpp
- Main/src/ScoreScreen.cpp
- Main/src/Scoring.cpp
- Main/src/SettingsScreen.cpp
- Main/src/SongSelect.cpp
- Main/stdafx.h
- bin/skins/Default/scripts/gameplay.lua
- bin/skins/Default/scripts/result.lua
Note: this PR is incompatible with #374 
- Custom window settings for perfects, nears, and holds
- The timing windows are saved (on replay files and in the DB) for every replays.
- Relevant infos are passed to skins via `gameplay.hitWindow` and `result.hitWindow`
- There are two preset window values
- Normal: 46/92/138ms
- Hard: 23/46/138ms
- **Any opinions on which value to set for hold window?**
- To prevent abusing, window values wider than the normal window is not settable by default.
- Even though the wider values can be set by editing the config file directly, the default skin would display "Expand Judge" for gameplay and result screens.
- Also, for wide timing windows the score will not be saved.
- For multiplayers, the normal timing window is forced.
This is the first part of my …
> Customizable timing window

- Shared/include/Shared/StringEncoding.hpp
- Shared/include/Shared/StringEncodingConverter.hpp
- Shared/include/Shared/StringEncodingHeuristic.hpp
- Shared/src/StringEncodingConverter.cpp
- Shared/src/StringEncodingDetector.cpp
- Shared/src/StringEncodingHeuristic.cpp
Fixes the problem where downloading [this chart](https://ksm.dev/songs/33eb99b0-e8cc-11ea-8e1b-6fa10e1fdc61) crashes.
There's no false-positives for EUC-JPs among test-cases, so enabling EUC-JP looks OK.
> Fixed crash related to unzipping EUC-JP archives

- Beatmap/src/MapDatabase.cpp
Ubuntu 20.04
g++ (Ubuntu 9.3.0-10ubuntu2)
```
/home/hinara/unnamed-sdvx-clone/Beatmap/src/MapDatabase.cpp:967:30: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
967 |   constexpr char* addQuery = "INSERT INTO PracticeSetups("
|                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
968 |    "chart_id, setup_title, loop_success, loop_fail, range_begin, range_end, fail_cond_type, fail_cond_value, "
|    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
969 |    "playback_speed, inc_speed_on_success, inc_speed, inc_streak, dec_speed_on_fail, dec_speed, min_playback_speed, max_rewind, max_rewind_measure"
|    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
> Make some strings const to prevent warning

- Audio/include/Audio/AudioBase.hpp
- Audio/include/Audio/Audio_Impl.hpp
- Audio/include/Audio/DSP.hpp
- Audio/src/Audio.cpp
- Audio/src/AudioBase.cpp
- Audio/src/AudioStreamBase.cpp
- Audio/src/DSP.cpp
- Main/include/Audio/AudioPlayback.hpp
- Main/src/Audio/AudioPlayback.cpp
- Main/src/Audio/GameAudioEffects.cpp
- Tests.Game/src/TestAudio.cpp
- Tests.Game/src/TestBeatmap.cpp
The first commit fixes #394.
The second commit is mainly to remove the dynamic allocation for `float* tempData`.
While there's no need to do so, I also moved buffer directly inside `Audio_Impl`.
As I ranted in #394, the audio processing still contains problems, but this should be enough for quick dirty fix for the crash.
> Fixed rare glitch (or crash) when FX is being hit.

- Audio/src/DSP.cpp
This fixes the game locking up in the following level, which uses a PitchShift filter with pitch=690.0-740.0
https://ksm.dev/songs/90b95e50-e2dc-11ea-9bfb-77e35c0197b2
> Fix crash when using out of range values for PitchShift effect

- Audio/include/Audio/DSP.hpp
- Audio/src/Audio.cpp
- Audio/src/DSP.cpp
- Main/src/Audio/GameAudioEffects.cpp
This is just to prevent the assert from triggering.
> Simple audio assert fix (add sampleRate to DSPs which does not need them)

- Shared/src/Unix/Files.cpp
For some Linux filesystems, d_type isn't supported and returns DT_UNKNOWN. In this case (and when there's a symbolic link to the directory), the file type needs to be checked directly.
> Added fallback directory check when d_type is UNKNOWN/LNK

- Audio/src/AudioStreamMa.cpp
- Audio/src/Sample.cpp
Fix discovered [here](https://github.com/mackron/miniaudio#vorbis-decoding).
This has fixed an issue I've been having where .ogg FX chip samples wouldn't load. Specifically, `ma_decode_file()` would give a return code of `-1`, a generic error code, when trying to load .ogg sound files.
> Fix Ogg Vorbis sound files not decoding

- Main/src/Background.cpp
- bin/skins/Default/shaders/examples/foreground/scanlines.fs
- docs/source/bgfg.rst
Using `fb_tex` in the foreground shader crashed USC. This PR fixes that.
Also, changed the name to `texFrameBuffer` for clearness.
> Fixed a bug that fb_tex didn't work properly.

- Main/CMakeLists.txt
- Main/include/ItemSelectionWheel.hpp
This PR changes how USC chooses a random chart when a player presses F2. Rather than generating a random number each time, it generates a randomized list of all the charts. This list is then looped through each time the user presses F2 until it has been exhausted, at which point the list will be re-generated again. This removes the possibility of a chart being randomly picked multiple times in a short period and gives a better user experience.
An additional change in this PR is a small change to the CMake configuration. This was necessary to fix an error while building using Visual Studio.
> feat(song select): Improve random chart algorithm

- Main/include/Application.hpp
- Main/include/GameConfig.hpp
- Main/include/IR.hpp
- Main/include/LuaRequests.hpp
- Main/include/SkinIR.hpp
- Main/src/Application.cpp
- Main/src/GameConfig.cpp
- Main/src/IR.cpp
- Main/src/ScoreScreen.cpp
- Main/src/SettingsScreen.cpp
- Main/src/SkinHttp.cpp
- Main/src/SkinIR.cpp
- Main/src/SongSelect.cpp
- bin/skins/Default/config-definitions.json
- bin/skins/Default/scripts/result.lua
- bin/skins/Default/scripts/songselect/background.lua
- bin/skins/Default/scripts/songselect/songwheel.lua
Hi,
I've spent some time over the past week or so implementing Internet Ranking features into USC, which follow a well-defined protocol that anyone can implement. In addition to that, I have created an example IR server, which anyone can instantly set up and run themselves, in much the same way as is possible with the multiplayer server.
The current version of the protocol, as well as a documentation of skinning changes can be found [here](https://uscir.readthedocs.io/en/latest/index.html)
The example server can be found [here](https://github.com/ereti/usc-ir-server), and I am also currently running it on [my website](https://uscir.catgirl.energy), if you would wish to view an example of it in action without having to set it up yourself. Please note that the only scores and charts that …
> IR Support

- Main/src/Application.cpp
#436 but on the master branch, as I believe that "false crash dumps" is harmful to users reporting a genuine, game-affecting crash.
> Fix occasional crashes caused by wrong free order of font res

- .github/workflows/build.yml
- Audio/CMakeLists.txt
- Beatmap/CMakeLists.txt
- CMakeLists.txt
- GUI/CMakeLists.txt
- Graphics/CMakeLists.txt
- Main/CMakeLists.txt
- Shared/CMakeLists.txt
- Shared/include/Shared/Buffer.hpp
- Shared/src/Buffer.cpp
- Tests.Game/CMakeLists.txt
- Tests.Shared/CMakeLists.txt
- Tests/CMakeLists.txt
- third_party/CMakeLists.txt
Compile time on a 6-core 12-thread CPU (very non-scientific; ran each twice in a row and used later value to reduce deviations caused by file caching):
- Debug: **1m 23s** to **37s**
- Release: **1m 50s** to **55s**
Sadly, CI doesn't seem to be affected by this.
Forgot to add /MP for test projects but it doesn't matter a lot.
> Bumped up to C++17 and enabled /MP for all projects

- bin/skins/Default/scripts/gameplay.lua
Rationale is to make it clear to skin devs that the crit line offset should not be used for the console.
> Use separate function to calculate console rotation offset

- Beatmap/src/MapDatabase.cpp
- Main/include/HitStat.hpp
- Main/include/Scoring.hpp
- Main/src/HitStat.cpp
- Main/src/Scoring.cpp
Should be inline with SDVX.
Prereq. PR: #458 to pass pipelines.
> Increase caps on near, hold timing windows

- Main/src/Game.cpp
- Main/src/Scoring.cpp
This applies regardless if the key beam was spawned from a crit, near or idle state.
> Always start fading key beam when a hold has passed

- Audio/include/Audio/DSP.hpp
- Audio/src/DSP.cpp
- Beatmap/src/BeatmapFromKSH.cpp
- Main/include/Audio/AudioPlayback.hpp
- Main/src/Audio/AudioPlayback.cpp
- Main/src/Scoring.cpp
Laser FX mix values are now clamped to [0, 1], preventing dangerously loud audio FX. An issue with how FX parameters were parsed was also fixed, where a parameter with a decimal point and a percent sign was being interpreted as a whole number rather than a percentage.
> Clamp laser FX parameters, fix FX parameters being parsed incorrectly

- Main/include/Application.hpp
- Main/include/ChatOverlay.hpp
- Main/include/GameConfig.hpp
- Main/include/GuiUtils.hpp
- Main/src/Application.cpp
- Main/src/ChatOverlay.cpp
- Main/src/GameConfig.cpp
- Main/src/GuiUtils.cpp
- Main/src/MultiplayerScreen.cpp
- Main/src/SettingsScreen.cpp
- Main/stdafx.cpp
- Main/stdafx.h
This option has BasicNuklearGui instances share the same font atlas and font texture. Additionally there are two changes which improve the time it takes to initialize the nuklear font texture:
- Font baking is done in a background thread at startup if the option is enabled
- A pixel buffer is used to asynchronously upload a font texture (on non embedded builds)
From testing the font texture is about 250mb currently so this option is disabled by default on embedded
> Add option to save nuklear font texture between BasicNuklearGui instances

- Main/src/Input.cpp
This code was incorrectly treating a back button input as a laser input.
This resulted in an out of bounds array access, causing random left
laser inputs when hitting the back button.
> Fix out of bounds access on back button input

- .gitignore
- Audio/include/Audio/DSP.hpp
- Audio/src/DSP.cpp
- Beatmap/include/Beatmap/AudioEffects.hpp
- Beatmap/src/AudioEffects.cpp
- Beatmap/src/BeatmapFromKSH.cpp
- Main/src/Audio/GameAudioEffects.cpp
Fix duration params so they support absolute (s, ms) and relative (float) lengths.
Support `feedback`, `stereoWidth`, and `volume` params for custom flangers.
Comparison between KSM, fixed USC, and original USC using `#define_fx testFlanger type=Flanger;period=2;stereoWidth=25%` on white noise:
- Note the "folding" due to `stereoWidth` in the right channels of `KSM` and `USC fixed`.
- `USC orig` interpreted `period=2` as 2 ms.
> Fix and extend custom flangers

- Audio/include/Audio/DSP.hpp
- Audio/src/DSP.cpp
- Beatmap/include/Beatmap/AudioEffects.hpp
- Beatmap/src/AudioEffects.cpp
- Beatmap/src/BeatmapFromKSH.cpp
- Main/src/Audio/AudioPlayback.cpp
- Main/src/Audio/GameAudioEffects.cpp
- Tests.Game/src/TestAudio.cpp
Add support for all custom phaser params: `period`, `stage`, `loFreq`, `hiFreq`, `Q`, `feedback`, `stereoWidth`, `hiCutGain`
Additional misc changes:
- sample `mix` for effects instead of always setting it to `1.0` when enabled
- fix default effect params
- factor out biquad filters from BQFDSP
Comparison of KSM, USC (new), USC (old) using `#define_fx testFx type=Phaser;period=1;stage=12;loFreq=5000Hz;hiFreq=15000Hz;Q=0.5;feedback=25%;stereoWidth=25%;hiCutGain=-20.0dB;mix=0%>75%`:
> Extend custom phasers

- Main/include/IR.hpp
- bin/skins/Default/scripts/result.lua
Adds the new 22 Accepted code to IR.hpp and updates the default skin to understand it.
Docs are [here](https://uscir.readthedocs.io/en/latest/) as always, but in summary, the purpose of the new code is for IRs that hold new charts in a queue until X unique players have played them to indicate that they have saved the submitted score but that it will not yet show up (as a record, or in the leaderboard, et cetera).
> Update USC-IR support to v0.3.2-a

- Main/src/ChallengeResult.cpp
- Main/src/ChallengeSelect.cpp
- Main/src/Game.cpp
- Main/src/ScoreScreen.cpp
- Main/src/SettingsScreen.cpp
- Main/src/Test.cpp
- Main/src/TitleScreen.cpp
- Main/src/TransitionScreen.cpp
This fixes ButtonBindingScreen, LaserSensCalibrationScreen and TransitionScreen's OnKeyPressed() override not actually overriding their base function. Also properly mark a bunch of IApplicationTickable overrides to prevent this from happening again.
> Clean up IApplicationTickable function overrides

- .github/workflows/build.yml
Also preserves the execute permission by packing the game into a `.tar.gz` before uploading it.
(Manual workflow trigger is for testing)
> Make AppImage executable using `chmod`

- Beatmap/include/Beatmap/BeatmapPlayback.hpp
- Beatmap/src/BeatmapPlayback.cpp
- Main/src/Game.cpp
- Hid/Sud status
- Speed mod status
- Playback status
Also some reverts for `BeatmapPlayback::Reset` from #547 is included, which should not change the behavior...
**Important note: #549 is NOT fixed**, but merging this PR would automatically close it, so **it must be manually re-opened afterwards**.
> Added more informations on debug HUD (for investigating #549)

- Main/src/Game.cpp
- Main/src/HitStat.cpp
- bin/skins/Default/scripts/result.lua
Fixed bugs:
* Badge desc displayed as 'TODO' on IR scores
* Timing window details were incorrectly shown for the default timing window
* UCing on HARD judgement was not equivalent to PUCing on NORMAL judgement
Also, "automatically set timing window" feature was modified a little bit so that it doesn't override manually-set timing offsets
> Fixing a few bugs related to the result screen and timing windows.

- Beatmap/src/BeatmapPlayback.cpp
- bin/skins/Default/shaders/button.fs
- bin/skins/Default/shaders/holdbutton.fs
- bin/skins/Default/shaders/laser.fs
- bin/skins/Default/shaders/trackCover.fs
Fixed following bugs:
- Game crashes on entering calibration mode
- Hid/sud is not working correctly when fade window is set to 0
- Measure bar does not show for long charts or charts with scroll speed modifier
> Fix bugs related to calibration mode and hid/sud

- build.linux
Fixes #557.
I tested both FreeType and zlib with their latest versions and confirmed that both worked, so I bumped both of their versions.  
zlib has a download archive with all versions so I linked to the archive download so that the link won't break with the next update.
> Update dead links in build.linux

- updater/CMakeLists.txt
- updater/src/Downloader.cpp
- updater/src/Downloader.hpp
- updater/src/Extractor.cpp
- updater/src/Extractor.hpp
- updater/src/updater.cpp
For me and some other people, some network problem interrupted the update process, and the updater not checking the error code of `cpr::Response` resulted in corrupted game directory.
While this can be resolved by running the updater until it succeedes, it's very annoying.
Using the HTTP range header, the updater now tries to download from where it was after the download is interrupted. Also few other improvents are made.
Important fixes:
- It tries to download partial content not yet downloaded yet, unless previous attempt could not download anything.
- I think that sleeping before retrying in this case is unnecessary.
Additional changes:
- The intention is to reuse the code for Nautica downloads (in future).
- Removed ARCHIVE_EXTRACT_PERM
- Added ARCHIVE_EXTRACT_SECURE_NODOTDOT and …
> Improved updater for Windows

- Main/src/Application.cpp
... and made the log a little bit more helpful by roughly specifying which part the error has happened. So far I've seen none.
The `OpenGL Error: 0000000000000502` log was happening during `SDL_GL_SwapWindow` so it's not our fault... right?
> Reduced amounts of 'OpenGL error' debug logs happening 

- Audio/src/AudioStreamBase.cpp
- Main/include/Audio/AudioPlayback.hpp
- Main/include/GameConfig.hpp
- Main/src/Audio/AudioPlayback.cpp
- Main/src/Audio/GameAudioEffects.cpp
- Main/src/Game.cpp
- Main/src/GameConfig.cpp
- Main/src/PracticeModeSettingsDialog.cpp
- Main/src/SettingsScreen.cpp
- It can get higher, but the current upper bound of x4.0 seems to be more than enough
- Two settings: one for speeds higher than x1.0 and one for speeds lower than x1.0
- Default setting for both are `true`
- Well, currently it almost works in this PR but it doesn't work for retrigger effects because of how it works :(
- Pre-rendering effects will make it work correctly, so I think that this is not a big problem now.
I think that this is enough to close #440, with pre-rendered effects.
> Add support for playback speeds higher than x1.0

- Main/src/Application.cpp
Fixed bug #646 where volume will revert to default value instead of user set value when loading into title screen for the first time.
> Fixed volume loading as default value

- .github/workflows/build.yml
- CMakeLists.txt
- README.md
- mac-cmake.sh
This PR simplifies the build process for MacOS by setting the library paths in the CMakeLists.txt file, essentially removing the need for `macos-cmake.sh` to exist.
It also fixes #471 and #654, which are related to `libjpeg` being shipped as a keg on ARM MacOS machines, making it so it's not symlinked to homebrew's prefix. This is due to it conflicting with `libjpeg-turbo`, which is (as far as I can tell) faster and ABI compatible, so I took the liberty of replacing it entirely. If this is undesirable, let me know and I can instead have cmake link with the correct path for `libjpeg` as I did with `libarchive`.
> Fix missing libjpeg in ARM MacOS and set MacOS libraries in CMakeLists.txt

- .gitmodules
- CMakeLists.txt
- Main/include/LuaRequests.hpp
- Main/src/ScoreScreen.cpp
- Main/src/SkinHttp.cpp
- Main/src/SkinIR.cpp
- Main/stdafx.h
- cmake/Modules/FindCPR.cmake
- third_party/CMakeLists.txt
This PR updates CPR to 1.10.5, as well as adds a CMake option to use the system's CPR instead of the one in submodules. The update allows the game to be compiled with a more recent version of CURL, and the latter is mostly just for convenience when packaging the game for Nix in the near future.
> Update to CPR 1.10.5

- Main/src/Application.cpp
- README.md
This is somewhat of a stopgap solution to the issue of the game failing to launch when `gameDir` is set to a directory without the necessary assets. USC is shipped with the assets needed to at least run, so it can handle this scenario by copying them over to `gameDir` when it is detected to be empty. For my nix package I wrapped the executable with a bash script that does this at runtime, but it makes sense to me for the game to do this.
A more elegant solution would be to separate the specification of asset paths (for example, implementing `-skinsdir`, `-fontsdir`, `-songsdir`, etc), as well as allowing these options to contain multiple paths to be searched, akin to the colon-separated list of directories in `$PATH`. In this scenario, the game could always search the executable path for …
> Set gameDir to $XDG_DATA_HOME and copy assets on initialization

- CMakeLists.txt
- Main/src/Application.cpp
Building on #645, I wanted to make things easier for packaging the application for things like flatpak.
- Add install targets to cmake file. This allows packaging tools to know where to put the compiled binary and game files. This shouldn't affect much since it should only perform operations when explicitly running `make install`.
- Added search against `XDG_DATA_DIRS` for assets. This is usually set by the distro or packaging system and defines where a package's assets should be located.
If you're okay with merging these changes,  I do have a flatpak manifest that is ready to go if you're interested in submitting to [flathub](https://flathub.org/)!
Let me know if you have any questions, or would like any changes. Thanks!
> Changes for easier Linux packaging
