README.md

Added use plain text notice
Fixed silly typo

Update README.md, closes #3

---

Main/SongSelect.cpp

This prevents loading the preview every time you scrub over a song.

Delay preview audio loading by 15 ticks

---

README.md

- Added:
- "Skinning support" to features list
- "Fix linux support" to TODO list
- Removed:
- Unnecessary backslashes on '*.ksh'
- Unnecessary whitespace in 'Controls'
- Changed SDVX link
- Rephrased "Real time FX" in features list
- Reformated "Main.cfg" paragraphs
- Made command text smaller to fit in one line in web view
- Moved "Not reqiured to build from source" from 'How to build' to 'Windows' (There's no pre-built exe for Linux... yet!)
- Escaped backslash on line 67/71 (Visual Studio)
- Spelling and grammar

Cleaned up and updated README.md a lot

---

Main/GUI/SongSelectItem.cpp
Main/GUI/SongSelectItem.hpp
Main/SongFilter.cpp
Main/SongFilter.hpp
Main/SongSelect.cpp
Main/SongSelect.hpp

Also looked into and temporarily fixed bugs with re-selecting charts after leaving gameplay.

Improved level filtering

---

Main/Camera.cpp
Main/Camera.hpp

but they work pretty well so far
I want to update them to be like piecewise functions or maybe a quadratic, but this is pretty close to what it needs to be otherwise with easy to visualize math functions.

Camera changes

---

Main/Game.cpp
Main/Input.cpp
Main/Input.hpp
Main/SongSelect.cpp

everything past the start screen (minus text search) should totally support controller inputs. This adds back, which I think is everything so far? No more need to press escape when you have a controller in front of you.

More controller functions

---

Beatmap/include/Beatmap/BeatmapObjects.hpp
Beatmap/include/Beatmap/BeatmapPlayback.hpp
Beatmap/src/BeatmapFromKSH.cpp
Beatmap/src/BeatmapPlayback.cpp
Main/Background.cpp
Main/Camera.cpp
Main/Camera.hpp
Main/Game.cpp
Main/Track.cpp
Main/Track.hpp

The name of this branch is kinda shitty oops.
This adds some really fun features for charters to play with; some which should've been there before which KShoot already supports, and some new ones (with more on the way, just not yettt)
Fixes included in this PR:
- Left laser roll keep now calculated correctly.
- Hold BT/FX particle emitters should always be positioned properly.
- Zoom controls always yield values, even before the first defined point. The beginning of charts will always use the first defined zoom control point as the default zoom value.
New features included in this PR:
- Tweaked base highway values (which will likely keep happening until all camera stuffs are added, and everyone should, of course, approve them since that's what you'll see the most of!)
- Update the …

Add a bunch of gameplay features for charters

---

Main/SongSelect.cpp

The correct values are now stored to and loaded from the config to retain selected map information, and Lua gets its values updated on a skin reload

Fix selection index issues

---

Main/SongSelect.cpp
README.md

Add illustrator to lua

---

.gitmodules
Audio/CMakeLists.txt
Audio/include/Audio/AudioStreamBase.hpp
Audio/src/AudioStream.cpp
Audio/src/AudioStreamBase.cpp
Audio/src/AudioStream_ma.cpp
Audio/src/Sample.cpp
CMakeLists.txt
Graphics/include/Graphics/Image.hpp
Graphics/include/Graphics/MeshGenerators.hpp
Graphics/include/Graphics/OpenGL.hpp
Graphics/include/Graphics/RenderQueue.hpp
Graphics/src/Font.cpp
Graphics/src/SpriteMap.cpp
Main/LaserTrackBuilder.cpp
Shared/include/Shared/Margin.hpp
Shared/include/Shared/Rect.hpp
third_party/CMakeLists.txt

Replaces the barely working wav decoder and also adds flac support.

Add new audio decoder

---

Main/Track.cpp

Change holdButtonMaterial->blendMode to Normal.

---

Tests.Game/Main.cpp

I got an compilation error when trying to build the project under VS 2019. Adding the include fixed it for me.

Compilation fix

---

Beatmap/src/MapDatabase.cpp

Fix issue with creating tables

---

Main/GameConfig.cpp
Main/GameConfig.hpp
Main/Input.cpp
Main/Input.hpp

This PR permit to use some kind of controller with no infinite input like an XBox controller

Add Direct Mode (No delta) for Controller

---

Audio/src/AudioStreamBase.cpp
Graphics/src/Window.cpp
Main/Application.cpp
Main/Game.cpp
Main/MultiplayerScreen.cpp
Main/SettingsScreen.cpp
Main/SongSelect.cpp
Main/TCPSocket.cpp
Main/TransitionScreen.cpp
Shared/src/Jobs.cpp
Shared/src/Unix/Path.cpp
Tests.Game/TestAudio.cpp
Tests/src/TestManager.cpp

Remove useless formatting

---

Main/Application.cpp
Main/LaserTrackBuilder.cpp

Fixes a crash when the user's skin isn't found, will fallback to the default skin.
#138

Fix crash if skin not found

---

Beatmap/src/MapDatabase.cpp
Main/SongSelect.cpp

Fix crash when removing songs

---

Shared/src/Windows/Path.cpp

Fix IsDirectory

---

Main/Game.cpp

Remove special character

---

Main/src/Scoring.cpp

Disable bounce protection before map begin

---

.gitignore

I guess I should have included these in the last PR but I noticed after I playtested my camera changes. Oh well.

Ignore replays folder and all skins except Default

---

Main/src/Background.cpp

This is a part of my attempt to make lua scripts safer. This change set focuses on the libraries allowed in the background lua scripts. We already only allow a small subset of libraries, but the package library and the require function can be problematic when asked to load DLLs. Here I have removed the C searchers (which look for DLLs), package.loadlibrary, and the cpath (which is used by require to load DLLs). This should remove ability to load arbitrary code as far as I know.
I also added better error messages for libraries that are disabled.
I don't think this should break any charts, as charts should not be loading dlls in the first place.

Better sanitize libraries allowed in backgrounds

---

Main/src/Scoring.cpp

Remove sign check on unsigned value

---

Main/src/Game.cpp
docs/source/gameplay.rst

There was a problem where failing the mission in the practice mode w/o loop would result in wrong clear marks.
Added missing documentation for skinning the practice mode as a bonus.

Simple bug fix related to practice mode

---

Main/include/GameConfig.hpp
Main/src/GameConfig.cpp

Fix #423 
This move version to cpp file which is undesirable, but if #424 does not work then this is the only way.

[WIP] Fix GameConfig::VERSION (Source fix)Fix version

---

Main/include/Scoring.hpp
Main/src/Scoring.cpp

Seems to be better? Until I get access to EG this is probably the best workaround I can come up with.

Check early for slams

---

Main/src/Audio/OffsetComputer.cpp

Added bound checks for accessing `m_pcm`.

Fix crash by out-of-bound access from offset computer

---

Beatmap/src/BeatmapPlayback.cpp

Cause: `BeatmapPlayback::GetObjectsInViewRange` behaves incorrectly when `m_currObject` is before `m_playRange`

Fixed a regression in #515 (objects not visible for certain cases during practice mode)
